# Generated by Django 5.0.6 on 2024-07-13 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('BankAccountID', models.AutoField(primary_key=True, serialize=False)),
                ('AccountNumber', models.CharField(max_length=50)),
                ('BankName', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
                ('SwiftCode', models.CharField(max_length=50)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
